[package]
name = "hello_proc_macro"
version = "0.1.0"
authors = ["michele <michele.damico@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version="*", features=["full"]}
quote = "*"
proc-macro2 = "*"